### ISSUE TITLE
[Bug] if an Enum field is optional and has null value, the TryGet function should return false but not true.

### ISSUE THREAD

**Issue by JustusPan** [Cammin/LDtkUnity#44] opened 2022-12-14 13:59 UTC
![image](https://user-images.githubusercontent.com/10916383/207614503-648c77ba-e1cd-49dc-b3b7-1684a7d7a4b5.png)
if an Enum field is optional, when it's value is null
fields.TryGetEnum<KeyTypes>("KeyType", out var keyType)
then the return value of this TryGet should be false
but currently it returns true

**Comment by Cammin** [comment] 2022-12-14 18:24
In the XML documentation and the API docs, the return value is described as returning true if the field exists.  
![image](https://user-images.githubusercontent.com/55564581/207677290-62a72a3a-f20b-4d88-bf02-7145d5b66b5b.png)

**Comment by Cammin** [comment] 2024-09-04 21:47
Closing this, this was intended I believe

**Closed as completed by Cammin** 2024-09-04 21:47 UTC
